name: cook_book_app
description: App to hold all recipes you do know.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  camera_bloc: ^0.0.1

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  hive_generator: ^1.1.3
  build_runner: ^2.3.0

flutter:
  uses-material-design: true

